from classJogadores import Jogador
benzema = Jogador("Benzema","M","Real Madrid","França")
benzema.card()
mbappe = Jogador ("Mbappé","M","PSG","França")
mbappe.card()
formiga = Jogador("Formiga","F","PSG","Brasil")
formiga.card()
pele = Jogador("Pelé","M","Santos","Brasil")
pele.card()
Marta = Jogador("Marta","F","Orlando Pride","Brasil")
Marta.card()
Neymar = Jogador("Neymar","M","PSG","Brasil")
Neymar.card()
Debinha = Jogador("Debinha","F","Kansas City Current","Brasil")
Debinha.card()